### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizergit** [jamesdeperio/PocketLib#1]
Greetings, @jamesdeperio 

I'm a designer in development and an open source enthusiast. I was checking out cool projects like yours and noted that you could use a good looking scalable logo for it, I could try a few designs keeping the essence you already have but making it more scalable to smaller sizes. What do you think? It would be for free and you can't quit at whatever stage of the process you want.

Best regards.

**Comment by jamesdeperio** [comment]
Hi @michaelizergit ,
Sure why not. I appreciate your proposal. Let me see first.
Thanks

**Comment by michaelizergit** [comment]
Hello, I'm so sorry for disappearing I was finishing a semester. I want to resume the work as soon as possible just passing by to ask if you are still interested.

**Comment by jamesdeperio** [comment]
Hello @michaelizergit , it's okay. Just ping me when you are done.  
Here is my email [jamespatrickdeperio@outlook.com](jamespatrickdeperio@outlook.com)
